fix: Fix regression after making retries configurable
This fixes the following error:
```
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```