Fix "AttributeError: 'Incident' object has no attribute 'azure'"
d836f9d removed most code for handling azure but missed this one spot
which now causes a problem:

```
AttributeError: 'Incident' object has no attribute 'azure'
```